name: CI

on:
  pull_request:
  push:

permissions: write-all

jobs:
  # ================
  # BUILD AND TEST JOB
  # ================
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: ["stable"] # '1.16', '1.17', '1.18', etc.
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build
        run: go build -v -o /dev/null .
      - name: Test
        run: go test -v ./...

  # ================
  # RELEASE BINARIES (on push "v*" tag)
  # ================
  release_binaries:
    name: Release Binaries
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --config .github/goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ================
  # RELEASE DOCKER IMAGES (on push "v*" tag)
  # ================
  release_docker:
    name: Release Docker Images
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: xxx
          password: xxx
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: jpillora/chisel
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{

#added this
#added more
#added
