name: CI

on:
  push:
  pull_request:

jobs:
  # ================
  # TEST JOB
  #   runs on every push and PR
  #   runs based on matrix configuration
  # ================
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build -v -o /dev/null .
      - name: Test
        run: go test -v ./...